### PR TITLE
Updates for new multi- and complex mapping functionality in basin3d

### PR DESCRIPTION
**Pull request by dschristianson**
Issue #3, #6, #7

Details:
- Updated timeseries.py to work with new basin3d multi- and complex mapping feature
- Updated related tests
- Added conftest.py file to enable running integration tests from command line using `--runintegration`

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

NOTE: GitHub Actions will not pass until corresponding PR on basin3d is merged into develop.
All tests passed when pointing to the issue branch in basin3d in the requirements.txt file.

- [x] Unit tests
- [x] Integration tests 
- [x] Test coverage >= 90%
- [x] Flake8 Tests 
- [x] Mypy Tests 

### Test Configuration
* Python Version: 3.8.13

## PR Self Evaluation

- [x] My code follows the agreed upon best practices
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests or modified existing tests that prove my fix is effective or that my feature works
- [x] Existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in the appropriate modules
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by vchendrix — CHANGES_REQUESTED** [review]
@dschristianson Looks like there are some test errors.

**Comment by dschristianson** [comment]
> @dschristianson Looks like there are some test errors.

Yeah, same mypy errors I think...

**Comment by dschristianson** [comment]
@vchendrix: ready for your review. I did not add support for 3.10. LMK if you'd like that bundled in this PR. Thx!

**Comment by vchendrix** [comment]
> @vchendrix: ready for your review. I did not add support for 3.10. LMK if you'd like that bundled in this PR. Thx!
@dschristianson I think that is fin.

**Review by vchendrix — APPROVED** [review]
Looks great!

**Pull request merged**
